#---------------------------------
# Repository (GitHub)
#---------------------------------

# Set clone depth to speed up clone
clone_depth: 10
# Folder to clone the repository to
clone_folder: C:\_git\Stomp.Net

# Skipping commits with noCI in commit message
skip_commits:
  message: \bnoCI\b

#---------------------------------
# Notifications
#---------------------------------
notifications:
  # Slack
  - provider: Slack
    auth_token:
      secure: Vr01F/A4n7oVgaBKuoKtJfRw4O0GDI/TdlktqvEVHm1Q2D8qkJRQ5Cp9CxIaPklQWY8yfl7EkExMNMdhHj8sDYZygO9FnbOFgtPlyWeGKWg=
    channel: '#build'

#---------------------------------
# Before build
#---------------------------------

# Version format
version: 2.3.0.{build}

pull_requests:
  # Do not increment build number for pull requests
  do_not_increment_build_number: true

nuget:
  # Do not publish NuGet packages for pull requests
  disable_publish_on_pr: true

#---------------------------------
# Build configuration
#---------------------------------

# Set the build worker image
image: Visual Studio 2022
build:
  verbosity: minimal
  
# Build configuration
configuration: Release

#---------------------------------
# Build
#---------------------------------

# Script to build all the solution
build_script:
- ps: .Build\Build.ps1

#---------------------------------
# After build
#---------------------------------

# Define artifacts
artifacts:
  - path: .Output
  - path: '.Output\**\*.nupkg'
    name: NuGetPackage.nupkg

# Deploy to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: EuMTEOZnx2khhY8a77sGO/tC4STC3rZe2eABB2Bq33dXoIHnATxMnMnMoOohn7eQ
  artifact: /.*\.nupkg/
  on:
    # Only publish from the master branch
    branch: master